CREATE TABLE IF NOT EXISTS TB_SAPATO (
    ID SERIAL PRIMARY KEY, NOME VARCHAR(255) NOT NULL, MARCA VARCHAR(255) NOT NULL, PRECO DECIMAL(10, 2) NOT NULL, DESCRICAO VARCHAR(255), PRODUTO_STATUS VARCHAR(50) NOT NULL, CATEGORIA_BASE VARCHAR(50) NOT NULL, TAMANHO INTEGER NOT NULL, IMAGEM BYTEA
);